<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'Это программное обеспечение предоставляется на разных языках. Используйте этот инструмент, чтобы установить язык системы по умолчанию.';
$lang['language_app_name'] = 'Язык';
$lang['language_code_ca_es'] = 'Каталонский';
$lang['language_code_cs_cz'] = 'Чешский';
$lang['language_code_da_dk'] = 'Датский';
$lang['language_code_de_de'] = 'Немецкий';
$lang['language_code_en_us'] = 'Английский (США)';
$lang['language_code_es_es'] = 'Испанский';
$lang['language_code_fa_ir'] = 'Персидский';
$lang['language_code_fi_fi'] = 'Финский';
$lang['language_code_fr_fr'] = 'Французский';
$lang['language_code_gr_gr'] = 'Греческий';
$lang['language_code_hu_hu'] = 'Венгерский';
$lang['language_code_id_id'] = 'Индонезийский';
$lang['language_code_it_it'] = 'Итальянский';
$lang['language_code_my_mm'] = 'Бирманский';
$lang['language_code_nl_nl'] = 'Голландский';
$lang['language_code_no_no'] = 'Норвежский';
$lang['language_code_pl_pl'] = 'Польский';
$lang['language_code_pt_br'] = 'Португальский (Бразилия)';
$lang['language_code_pt_pt'] = 'Португальский';
$lang['language_code_ro_ro'] = 'Румынский';
$lang['language_code_ru_ru'] = 'Русский';
$lang['language_code_sk_SK'] = 'Словацкий';
$lang['language_code_sl_sl'] = 'Словенский';
$lang['language_code_sv_se'] = 'Шведский';
$lang['language_code_tl_ph'] = 'Тагальский';
$lang['language_code_tr_tr'] = 'Турецкий';
$lang['language_code_zh_cn'] = 'Упрощенный китайский';
$lang['language_default_system_language'] = 'Язык системы по умолчанию';
$lang['language_keyboard'] = 'Клавиатура';
$lang['language_keyboard_is_invalid'] = 'Клавиатура является недействительной.';
$lang['language_language'] = 'Язык';
$lang['language_language_is_invalid'] = 'Язык является недействительным.';
$lang['language_update_my_login_session'] = 'Обновить мою сессию';
