<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'Diese Software wird in vielen verschiedenen Sprachen bereitgestellt.  Legen Sie hier die Standardsprache für Ihr System fest.';
$lang['language_app_name'] = 'Sprache';
$lang['language_code_ca_es'] = 'Katalanisch';
$lang['language_code_cs_cz'] = 'Tschechisch';
$lang['language_code_da_dk'] = 'Dänisch';
$lang['language_code_de_de'] = 'Deutsch';
$lang['language_code_en_us'] = 'Englisch (US)';
$lang['language_code_es_es'] = 'Spanisch';
$lang['language_code_fa_ir'] = 'Persisch';
$lang['language_code_fi_fi'] = 'Finnisch';
$lang['language_code_fr_fr'] = 'Französisch';
$lang['language_code_gr_gr'] = 'Griechisch';
$lang['language_code_hu_hu'] = 'Ungarisch';
$lang['language_code_id_id'] = 'Indonesisch';
$lang['language_code_it_it'] = 'Italienisch';
$lang['language_code_my_mm'] = 'Myanmar';
$lang['language_code_nl_nl'] = 'Niederländisch';
$lang['language_code_no_no'] = 'Norwegisch';
$lang['language_code_pl_pl'] = 'Polnisch';
$lang['language_code_pt_br'] = 'Portugiesisch (Brasielien)';
$lang['language_code_pt_pt'] = 'Portugiesisch';
$lang['language_code_ro_ro'] = 'Romänisch';
$lang['language_code_ru_ru'] = 'Russisch';
$lang['language_code_sk_SK'] = 'Slowakisch';
$lang['language_code_sl_sl'] = 'Slowenisch';
$lang['language_code_sv_se'] = 'Schwedisch';
$lang['language_code_tl_ph'] = 'Philipinisch';
$lang['language_code_tr_tr'] = 'Türkisch';
$lang['language_code_zh_cn'] = 'Vereinfachtes Chinesisch';
$lang['language_default_system_language'] = 'Standardsystemsprache';
$lang['language_keyboard'] = 'Tastaturlayout';
$lang['language_keyboard_is_invalid'] = 'Tastaturlayout ist ungültig.';
$lang['language_language'] = 'Sprache';
$lang['language_language_is_invalid'] = 'Sprache ist ungültig.';
$lang['language_update_my_login_session'] = 'Meine Login Session aktualisieren';
