<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'Este software é oferecido em diferentes idiomas. Use esta ferramenta para definir o idioma padrão do seu sistema.';
$lang['language_app_name'] = 'Idioma';
$lang['language_code_ca_es'] = 'Catalão';
$lang['language_code_cs_cz'] = 'Tcheco';
$lang['language_code_da_dk'] = 'Dinamarquês';
$lang['language_code_de_de'] = 'Alemão';
$lang['language_code_en_us'] = 'Inglês (US)';
$lang['language_code_es_es'] = 'Espanhol';
$lang['language_code_fa_ir'] = 'Persa';
$lang['language_code_fi_fi'] = 'Finlandês';
$lang['language_code_fr_fr'] = 'Francês';
$lang['language_code_gr_gr'] = 'Grego';
$lang['language_code_hu_hu'] = 'Húngaro';
$lang['language_code_id_id'] = 'Indonésio';
$lang['language_code_it_it'] = 'Italiano';
$lang['language_code_my_mm'] = 'Birmanês';
$lang['language_code_nl_nl'] = 'Holandês';
$lang['language_code_no_no'] = 'Norueguês';
$lang['language_code_pl_pl'] = 'Polonês';
$lang['language_code_pt_br'] = 'Português (Brasil)';
$lang['language_code_pt_pt'] = 'Português';
$lang['language_code_ro_ro'] = 'Romeno';
$lang['language_code_ru_ru'] = 'Russo';
$lang['language_code_sk_SK'] = 'Eslovaco';
$lang['language_code_sl_sl'] = 'Esloveno';
$lang['language_code_sv_se'] = 'Sueco';
$lang['language_code_tl_ph'] = 'Tagalog';
$lang['language_code_tr_tr'] = 'Turco';
$lang['language_code_zh_cn'] = 'Chinês Simplificado';
$lang['language_default_system_language'] = 'Idioma Padrão do Sistema';
$lang['language_keyboard'] = 'Teclado';
$lang['language_keyboard_is_invalid'] = 'Teclado Inválido';
$lang['language_language'] = 'Idioma';
$lang['language_language_is_invalid'] = 'Idioma Inválido';
$lang['language_update_my_login_session'] = 'Atualizar minha Sessão de Login';
