<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'ဤ software သည္ ဘာသာစကားမ်ားစြာျဖင္႔ စီစဥ္ေပးႏိုင္သည္။     မတူညီေသာ ဘာသာစကားကို စနစ္တြင္အသံုးျပဳရန္ ဒီ tool ကိုသံုးပါ။';
$lang['language_app_name'] = 'ဘာသာစကား';
$lang['language_code_ca_es'] = 'Catalan';
$lang['language_code_cs_cz'] = 'Czech';
$lang['language_code_da_dk'] = 'Danish';
$lang['language_code_de_de'] = 'German';
$lang['language_code_en_us'] = 'English (US)';
$lang['language_code_es_es'] = 'Spanish';
$lang['language_code_fa_ir'] = 'Persian';
$lang['language_code_fi_fi'] = 'Finnish';
$lang['language_code_fr_fr'] = 'French';
$lang['language_code_gr_gr'] = 'Greek';
$lang['language_code_hu_hu'] = 'Hungarian';
$lang['language_code_id_id'] = 'Indonesian';
$lang['language_code_it_it'] = 'Italian';
$lang['language_code_my_mm'] = 'Burmese';
$lang['language_code_nl_nl'] = 'Dutch';
$lang['language_code_no_no'] = 'Norwegian';
$lang['language_code_pl_pl'] = 'Polish';
$lang['language_code_pt_br'] = 'Portuguese (Brazil)';
$lang['language_code_pt_pt'] = 'Portuguese';
$lang['language_code_ro_ro'] = 'Romanian';
$lang['language_code_ru_ru'] = 'Russian';
$lang['language_code_sk_SK'] = 'Slovak';
$lang['language_code_sl_sl'] = 'Slovenian';
$lang['language_code_sv_se'] = 'Swedish';
$lang['language_code_tl_ph'] = 'Tagalog';
$lang['language_code_tr_tr'] = 'Turkish';
$lang['language_code_zh_cn'] = 'Simplified Chinese';
$lang['language_default_system_language'] = 'ပံုေသ ဘာသာစကား';
$lang['language_keyboard'] = 'လက္ကြက္';
$lang['language_keyboard_is_invalid'] = 'လက္ကြက္ မွားယြင္းေနသည္။';
$lang['language_language'] = 'ဘာသာစကား';
$lang['language_language_is_invalid'] = 'ဘာသာစကား မွားယြင္းေနသည္။';
$lang['language_update_my_login_session'] = 'မိမိ Login session ကို မြမ္းမံပါ။';
