<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = '本软件提供多种语言支持，这里可以设置系统默认语言。';
$lang['language_app_name'] = '语言';
$lang['language_code_ca_es'] = 'Catalan';
$lang['language_code_cs_cz'] = 'Czech';
$lang['language_code_da_dk'] = 'Danish';
$lang['language_code_de_de'] = 'German';
$lang['language_code_en_us'] = 'English (US)';
$lang['language_code_es_es'] = 'Spanish';
$lang['language_code_fa_ir'] = 'Persian';
$lang['language_code_fi_fi'] = 'Finnish';
$lang['language_code_fr_fr'] = 'French';
$lang['language_code_gr_gr'] = 'Greek';
$lang['language_code_hu_hu'] = 'Hungarian';
$lang['language_code_id_id'] = 'Indonesian';
$lang['language_code_it_it'] = 'Italian';
$lang['language_code_my_mm'] = 'Burmese';
$lang['language_code_nl_nl'] = 'Dutch';
$lang['language_code_no_no'] = 'Norwegian';
$lang['language_code_pl_pl'] = 'Polish';
$lang['language_code_pt_br'] = 'Portuguese (Brazil)';
$lang['language_code_pt_pt'] = 'Portuguese';
$lang['language_code_ro_ro'] = 'Romanian';
$lang['language_code_ru_ru'] = 'Russian';
$lang['language_code_sk_SK'] = 'Slovak';
$lang['language_code_sl_sl'] = 'Slovenian';
$lang['language_code_sv_se'] = 'Swedish';
$lang['language_code_tl_ph'] = 'Tagalog';
$lang['language_code_tr_tr'] = 'Turkish';
$lang['language_code_zh_cn'] = 'Simplified Chinese';
$lang['language_default_system_language'] = '系统默认语言';
$lang['language_keyboard'] = '键盘';
$lang['language_keyboard_is_invalid'] = '键盘布局无效';
$lang['language_language'] = '语言';
$lang['language_language_is_invalid'] = '语言无效';
$lang['language_update_my_login_session'] = '更新登陆会话';
