<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'Denna programvara finns för många olika språk.  Använd detta verktyg för att ställa in det förvalda språket för ditt system.';
$lang['language_app_name'] = 'Språk';
$lang['language_code_ca_es'] = 'Katalanska';
$lang['language_code_cs_cz'] = 'Tjeckiska';
$lang['language_code_da_dk'] = 'Danska';
$lang['language_code_de_de'] = 'Tyska';
$lang['language_code_en_us'] = 'Engelska (US)';
$lang['language_code_es_es'] = 'Spanska';
$lang['language_code_fa_ir'] = 'Persiska';
$lang['language_code_fi_fi'] = 'Finska';
$lang['language_code_fr_fr'] = 'Franska';
$lang['language_code_gr_gr'] = 'Grekiska';
$lang['language_code_hu_hu'] = 'Ungerska';
$lang['language_code_id_id'] = 'Indonesiska';
$lang['language_code_it_it'] = 'Italienska';
$lang['language_code_my_mm'] = 'Burmesiska';
$lang['language_code_nl_nl'] = 'Holländska';
$lang['language_code_no_no'] = 'Norska';
$lang['language_code_pl_pl'] = 'Polska';
$lang['language_code_pt_br'] = 'Portugisiska (Brasilien)';
$lang['language_code_pt_pt'] = 'Portugesiska';
$lang['language_code_ro_ro'] = 'Ungerska';
$lang['language_code_ru_ru'] = 'Ryska';
$lang['language_code_sk_SK'] = 'Slovakiska';
$lang['language_code_sl_sl'] = 'Slovenska';
$lang['language_code_sv_se'] = 'Svenska';
$lang['language_code_tl_ph'] = 'Tagalog';
$lang['language_code_tr_tr'] = 'Turkiska';
$lang['language_code_zh_cn'] = 'Förenklad Kinesiska';
$lang['language_default_system_language'] = 'Förvalt språk för systemet';
$lang['language_keyboard'] = 'Tangentbord';
$lang['language_keyboard_is_invalid'] = 'Ogiltigt tangentbord.';
$lang['language_language'] = 'Språk';
$lang['language_language_is_invalid'] = 'Ogiltigt språk.';
$lang['language_update_my_login_session'] = 'Uppdatera min inloggningssession';
