<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['language_app_description'] = 'To oprogramowanie oferuje wiele różnych wersji językowych.  Użyj tego narzędzia aby zmienić domyślny język systemowy.';
$lang['language_app_name'] = 'Język';
$lang['language_code_ca_es'] = 'Kataloński';
$lang['language_code_cs_cz'] = 'Czeski';
$lang['language_code_da_dk'] = 'Duński';
$lang['language_code_de_de'] = 'Niemiecki';
$lang['language_code_en_us'] = 'Angielski (Stany Zjednoczone)';
$lang['language_code_es_es'] = 'Hiszpański';
$lang['language_code_fa_ir'] = 'Perski';
$lang['language_code_fi_fi'] = 'Fiński';
$lang['language_code_fr_fr'] = 'Francuski';
$lang['language_code_gr_gr'] = 'Grecki';
$lang['language_code_hu_hu'] = 'Węgierski';
$lang['language_code_id_id'] = 'Indonezyjski';
$lang['language_code_it_it'] = 'Włoski';
$lang['language_code_my_mm'] = 'Burmański';
$lang['language_code_nl_nl'] = 'Holenderski';
$lang['language_code_no_no'] = 'Norweski';
$lang['language_code_pl_pl'] = 'Polski';
$lang['language_code_pt_br'] = 'Portugalski (Brazylia)';
$lang['language_code_pt_pt'] = 'Portugalski';
$lang['language_code_ro_ro'] = 'Rumuński';
$lang['language_code_ru_ru'] = 'Rosyjski';
$lang['language_code_sk_SK'] = 'Słowacki';
$lang['language_code_sl_sl'] = 'Słoweński';
$lang['language_code_sv_se'] = 'Szwecki';
$lang['language_code_tl_ph'] = 'Tagaloński';
$lang['language_code_tr_tr'] = 'Turecki';
$lang['language_code_zh_cn'] = 'Chiński uproszczony';
$lang['language_default_system_language'] = 'Domyślny język systemowy';
$lang['language_keyboard'] = 'Klawiatura';
$lang['language_keyboard_is_invalid'] = 'Podany typ klawiatury jest nieprawidłowy.';
$lang['language_language'] = 'Język';
$lang['language_language_is_invalid'] = 'Podany język jest nieprawidłowy';
$lang['language_update_my_login_session'] = 'Aktualizuj moją sesję logowania';
